### ISSUE TITLE
Estimated bounded queue length

### ISSUE THREAD

**Issue by danclien** [jberryman/unagi-chan#23]
Is there a way to get an estimated length for a bounded queue? It would be nice to be able to send that metric over to our monitoring system.

**Comment by jberryman** [comment]
Not with the current API. You could get an estimate by reading the input and output counters and subtracting them, with the obvious caveats that the value might be totally inaccurate sometimes since both reads won't be done atomically.

**Comment by jberryman** [comment]
https://github.com/jberryman/unagi-chan/pull/24
