### ISSUE TITLE
Please add to Stackage

### ISSUE THREAD

**Issue by lukehoersten** [jberryman/unagi-chan#31]
I'd like to move `unagi-streams` to stackage but need it's dependency `unagi-chan` to be in there first. [Here are the instructions](https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md#adding-a-package).

**Comment by shmish111** [comment]
I know @jberryman has previously said that he does not want to maintain this on stackage however I hope that he reconsiders, I too have a package I would like to be on stackage but it needs unagi-chan to be there.

**Comment by jberryman** [comment]
#16 #21 

I have plans to add some enhancements in the next few months (and need to improve some docs), so I'll investigate. I know someone was helping shepherd it on stackage at one point. I'd still appreciate it if anyone else wanted to help do that.

**Comment by lukehoersten** [comment]
I can easily add it to Stackage but it's recommended the maintainer add to Stackage themselves. Not much to it. You just add the package to a yaml list once and then do your normal maintenance work.
