### ISSUE TITLE
Support primitive-0.7.0

### ISSUE THREAD

**Issue by yaxu** [jberryman/unagi-chan#33]
unagi-chan doesn't build with the latest primitive version 0.7+ . I see @hvr has kindly fixed the upper bounds on hackage but still this causes dependency problems (e.g. https://github.com/tidalcycles/tidal-vis/issues/4 )

**Comment by jberryman** [comment]
Thanks for the report! Very busy next two weeks for me, traveling, so I may not be able to get to this until later in the month.

**Comment by yaxu** [comment]
No worries, happy travels !

**Comment by jberryman** [comment]
This should be fixed in the `travis` branch, but there's a test failure there I need to look into. Thanks again for your patience

**Comment by yaxu** [comment]
Thanks, I'm away another week myself but can have a look when I'm back

**Comment by jberryman** [comment]
Should be in 0.4.1.1

**Comment by yaxu** [comment]
Thanks again!
