### ISSUE TITLE
NOT_x86 discussion

### ISSUE THREAD

**Issue by angerman** [jberryman/unagi-chan#42]
Is there any discussion around the NOT_x86 CPP, that leads to warnings being emitted and subsequent failing builds with `-Wall`? I have to assume this is due to some ancient `atomic-primops` limitation?

Which instruction is used here that makes the warning necessary (and restricts the use to x86)?

**Comment by jberryman** [comment]
The message mentions this: fetch-and-add . I think a warning is probably overkill (or maybe not: if you are using the library on non-x86 would you have noticed a mention in the docs? Maybe performance of the CAS loop fallback would have been bug-report-level bad?)

Can I ask if you're using this successfully on something other than x86? I've never been able to really test it on other architectures

**Comment by angerman** [comment]
@jberryman can you point out where the CAS loop fallback is? I've been trying to locate the code that's responsible for this, but following https://github.com/jberryman/unagi-chan/search?q=fetch-and-add, only gives me the warnings.

The GHC source code (ghc-prim/cbits/atomic.c) makes me believe that unless we target aarch32, we defer to `__sync_fetch_and_add`.

Which would yield something like:
```
.LBB0_1:                                // =>This Inner Loop Header: Depth=1
        ldaxr   w8, [x8]
        add     w9, w8, w0
        stlxr   w10, w9, [x8]
        cbnz    w10, .LBB0_1
        mov     w0, w8
        ret
```
on aarch64 with clang targetting some generic armv8, or even
```
        ldaddal w0, w0, [x8]
       ret
```
while we'd generate something like the following for x86_64
```
        mov     eax, edi
        lock            xadd    dword ptr [rax], eax
        ret
```

I'm fully aware, I might just not be seeing it. If you could point out the CAS loop fallback that would be quite helpful!

**Comment by angerman** [comment]
And yes the fundamental question will be about using this on aarch64.

**Comment by jberryman** [comment]
IIRC we use `fetchAddIntArray` from `atomic-primops` which it looks like now calls a GHC primop of the same name https://hackage.haskell.org/package/atomic-primops-0.8.4/docs/src/Data.Atomics.html#fetchAddIntArray
My information is probably out of date or I'm misremembering that at one point this was a CAS loop. There's definitely no reason for a warning as long as the initial counter increment on the read and write sides is comparable to the x86 fetch-and-add. 
If you sort this out and want to open a PR to improve/fix the docs I'd definitely appreciate it; I haven't gotten to really look at how this performs or the code it generates on other architectures . Maybe there's just no reason for the warning or mention of "x86" anymore.

**Comment by bgamari** [comment]
There was indeed a fetch-and-add fallback long ago. However, this was fixed in https://gitlab.haskell.org/ghc/ghc/-/commit/eda73a3ad3fdd98cf877b25c3c984c6e1b2217fc.
