### ISSUE TITLE
  Blocking read available contents of Chan to list

### ISSUE THREAD

**Issue by Diamondy4** [jberryman/unagi-chan#44]
Is there a way to flush chan contents to a list? tryReadChan is definitely not what I want, as it removes elements from chan to Element with no way to place it back. NoBlocking version's stream can do what I want, but I need multiple producers/multiple consumers, where each consumer can try to flush whole Chan to list. I think I can go around it using MVar around OutChan, but that feels dirty. Is there anything like [flushTBQueue](https://hackage.haskell.org/package/stm-2.5.0.2/docs/Control-Concurrent-STM-TBQueue.html#v:flushTBQueue) that I missed?

**Comment by jberryman** [comment]
You want the `flush` operation to _never_ block right?

Hmm If you know you there are no concurrent readers running at the time then [`estimatedLength`](https://hackage.haskell.org/package/unagi-chan-0.4.1.4/docs/Control-Concurrent-Chan-Unagi-Bounded.html#v:estimatedLength) would give you the lower bound of items in the queue. But you need this to work with multiple consumers.

I can't really think of a way to make this work within the current design

**Comment by Diamondy4** [comment]
I have multiple consumers running every X seconds (at different time), who should flush whole chan contents into some IO action, so I think - yes - I want to never block, and want return immediately contents of chan (or [] when empty). TBQueue [flushTBQueue](https://hackage.haskell.org/package/stm-2.5.0.2/docs/Control-Concurrent-STM-TBQueue.html#v:flushTBQueue) is good but slow :<
